[package]
name = "sonar"
version = "0.1.0"
authors = ["Taylor Thompson <jamestthompson3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rodio = "0.11.0"
walkdir = "2.3.1"
